name = "sozayn-api"
main = "server/workers/index.js"
compatibility_date = "2023-03-01"

# Configure route
routes = [
  { pattern = "api.sozayn.com", custom_domain = true }
]

[vars]
# Define your production environment variables here
# Example:
# API_BASE_URL = "https://api.example.com"

[env.production]
# Production-specific settings
workers_dev = false
route = "api.sozayn.com/*"

[env.staging]
# Staging-specific settings
name = "sozayn-api-staging"
workers_dev = true

[build]
command = "npm run build:worker"
watch_dir = "server/workers"

[build.upload]
format = "modules"

# KV Namespace bindings
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"

# Durable Object bindings
# [[durable_objects.bindings]]
# name = "NOTIFICATIONS"
# class_name = "Notifications"

# D1 Database binding
# [[d1_databases]]
# binding = "DB"
# database_name = "sozayn-db"
# database_id = "your-d1-database-id"

# Service bindings allow connecting to other Workers
# [[services]]
# binding = "AUTH_SERVICE"
# service = "auth-service"