# Cloudflare Pages Configuration
[site]
name = "sozayn"
build_dir = "dist/public"
production_branch = "main"
ignore = [".git", "node_modules", "server"]

# Build settings
[build]
command = "npm run build"

# Environment Variables (these are only references, actual values are set in Cloudflare dashboard)
[env.production]
VITE_SUPABASE_URL = ""
VITE_SUPABASE_ANON_KEY = ""
VITE_STRIPE_PUBLIC_KEY = ""
API_URL = "https://api.sozayn.com"
CLOUDFLARE_ACCOUNT_ID = ""
CLOUDFLARE_API_TOKEN = ""

[env.staging]
VITE_SUPABASE_URL = ""
VITE_SUPABASE_ANON_KEY = ""
VITE_STRIPE_PUBLIC_KEY = ""
API_URL = "https://api-staging.sozayn.com"
CLOUDFLARE_ACCOUNT_ID = ""
CLOUDFLARE_API_TOKEN = ""

# Redirect rules - Single Page Application handling
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false